# 📊 Tarea – L1 Módulo 3 | Análisis de caso  
## La Librería NumPy: Aplicación de NumPy en el Análisis de Datos  

**Curso:** Fundamentos de Ingeniería de Datos  
**Estudiante:** Fabián Díaz  

---

## 📍 Situación Inicial

Una empresa de análisis financiero está desarrollando una herramienta para el procesamiento de grandes volúmenes de datos sobre el rendimiento de sus activos en la bolsa. Actualmente, su equipo trabaja con datos en formatos dispersos y estructuras poco optimizadas, lo que ralentiza los cálculos y dificulta la obtención de métricas en tiempo real.

El equipo ha decidido implementar **NumPy** para optimizar la carga, manipulación y análisis de datos, permitiendo realizar operaciones matemáticas y estadísticas de manera eficiente. Sin embargo, necesitan definir una estrategia clara para estructurar los datos, realizar cálculos rápidos y extraer información clave de forma ágil.

🎯 **Tu misión:** analizar esta situación y aplicar los conceptos aprendidos de NumPy para mejorar los procesos de manipulación y análisis de datos.

---

## 🔎 Descripción del Caso

En este caso, asumirás el rol de un **analista de datos** dentro del equipo de desarrollo de la empresa. Tu objetivo será optimizar la manipulación de datos utilizando **NumPy**, mejorando la eficiencia de los cálculos financieros y facilitando la toma de decisiones basada en métricas clave.

Trabajarás con **matrices y arreglos en NumPy** para realizar operaciones como:

- ✅ Creación y manipulación de arrays multidimensionales.  
- ✅ Aplicación de funciones estadísticas y matemáticas sobre los datos.  
- ✅ Indexación y selección eficiente de elementos dentro de los arrays.  
- ✅ Optimización del rendimiento computacional mediante el uso de **broadcasting** y operaciones vectorizadas.

---

➡️ A lo largo del análisis, se presentarán soluciones concretas que permitan mejorar el procesamiento de los datos y se justificará por qué **NumPy** es la herramienta adecuada para esta tarea.


Desarrollo:

1. Carga y estructuración de datos:

  ○ Crea un array NumPy con datos fi nancieros simulados (por ejemplo, precios de acciones en diferentes días).

  ○ Organiza los datos en una matriz de 5x5, donde cada fi la representa una acción y cada columna un día de cotización.

In [5]:
import numpy as np

# Simulación de precios (acciones x días)
precios = np.array([
    [100, 102, 101, 105, 107],
    [98, 97, 99, 100, 102],
    [150, 151, 149, 148, 150],
    [200, 198, 202, 205, 207],
    [50, 51, 49, 50, 52]
])

# Mostrar la matriz de precios
print("Matriz de precios simulados (acciones x días):")
print(precios)

# Información adicional
print("\nForma de la matriz:", precios.shape)
print("Tipo de datos:", precios.dtype)


Matriz de precios simulados (acciones x días):
[[100 102 101 105 107]
 [ 98  97  99 100 102]
 [150 151 149 148 150]
 [200 198 202 205 207]
 [ 50  51  49  50  52]]

Forma de la matriz: (5, 5)
Tipo de datos: int64


2. Análisis y transformación de datos:

  ○ Obtén el promedio, valor máximo y mínimo de cada acción a lo largo del tiempo.

  ○ Calcula la variación porcentual diaria de cada acción.

  ○ Aplica funciones matemáticas como logaritmo, exponencial o normalización sobre los datos.

In [6]:
# Promedio, máximo y mínimo por acción (eje horizontal)
promedios = precios.mean(axis=1)
maximos = precios.max(axis=1)
minimos = precios.min(axis=1)

print("Promedio de cada acción en los 5 días:")
print(promedios)

print("\nValor máximo de cada acción:")
print(maximos)

print("\nValor mínimo de cada acción:")
print(minimos)

# Variación porcentual diaria
variacion_pct = (precios[:, 1:] - precios[:, :-1]) / precios[:, :-1] * 100

print("\nVariación porcentual diaria de cada acción:")
print(variacion_pct)

# Logaritmo natural
log_precios = np.log(precios)

print("\nLogaritmo natural de los precios:")
print(log_precios)

# Normalización de los datos entre 0 y 1
precios_normalizados = (precios - precios.min()) / (precios.max() - precios.min())

print("\nPrecios normalizados (escala 0 a 1):")
print(precios_normalizados)


Promedio de cada acción en los 5 días:
[103.   99.2 149.6 202.4  50.4]

Valor máximo de cada acción:
[107 102 151 207  52]

Valor mínimo de cada acción:
[100  97 148 198  49]

Variación porcentual diaria de cada acción:
[[ 2.         -0.98039216  3.96039604  1.9047619 ]
 [-1.02040816  2.06185567  1.01010101  2.        ]
 [ 0.66666667 -1.32450331 -0.67114094  1.35135135]
 [-1.          2.02020202  1.48514851  0.97560976]
 [ 2.         -3.92156863  2.04081633  4.        ]]

Logaritmo natural de los precios:
[[4.60517019 4.62497281 4.61512052 4.65396035 4.67282883]
 [4.58496748 4.57471098 4.59511985 4.60517019 4.62497281]
 [5.01063529 5.01727984 5.00394631 4.99721227 5.01063529]
 [5.29831737 5.28826703 5.3082677  5.32300998 5.33271879]
 [3.91202301 3.93182563 3.8918203  3.91202301 3.95124372]]

Precios normalizados (escala 0 a 1):
[[0.32278481 0.33544304 0.32911392 0.35443038 0.36708861]
 [0.31012658 0.30379747 0.3164557  0.32278481 0.33544304]
 [0.63924051 0.64556962 0.63291139 0.6265822

3. Optimización y selección de datos:

    ○ Utiliza indexación avanzada para extraer información específica, como el rendimiento de una acción en un día determinado.

    ○ Aplica broadcasting para realizar operaciones sin necesidad de bucles.

In [7]:
# los índices parten desde 0
precio_dia4_accion3 = precios[2, 3]
print("Precio de la acción 3 en el día 4:", precio_dia4_accion3)

# Broadcasting: restar el valor del primer día a todos los días para cada acción
# Esto permite observar la variación absoluta diaria con respecto al primer día
diferencia_respecto_dia1 = precios - precios[:, [0]]
print("\nDiferencia de precios respecto al primer día para cada acción:")
print(diferencia_respecto_dia1)


Precio de la acción 3 en el día 4: 148

Diferencia de precios respecto al primer día para cada acción:
[[ 0  2  1  5  7]
 [ 0 -1  1  2  4]
 [ 0  1 -1 -2  0]
 [ 0 -2  2  5  7]
 [ 0  1 -1  0  2]]


4. Comparación con otros métodos:

    ○ Analiza cómo se podrían realizar estas tareas sin NumPy y compara la eficiencia en términos de código y rendimiento computacional.

## Conclusión

El uso de la librería NumPy permitió optimizar el análisis y manipulación de datos financieros, facilitando la aplicación de funciones estadísticas, operaciones vectorizadas y selección eficiente de datos.

Frente a métodos tradicionales, NumPy ofrece ventajas clave:

- Mayor rendimiento computacional.
- Reducción del uso de bucles.
- Operaciones más claras y compactas.
- Escalabilidad para grandes volúmenes de datos.

Gracias a estas características, NumPy se posiciona como una herramienta fundamental en el análisis de datos en entornos profesionales.
